### ISSUE TITLE
data binding issue: bound data does not appear on initial ng-click call, only persists on second click

### ISSUE THREAD

**Issue by cameragadget** [cameragadget/t_standup_app#1]
Current Sprint:
AAU I want to see my name displayed on the navbar when I am signed in.

Error:
I am not getting any error codes.  However, both the bound data and the ng-hide functions only fire after a secondary click of the button that triggers log in.

What I've done:
I've tried changing the order of my calls, reviewed my code, reviewed the docs and tried refactoring, and rewriting the function calls and am still getting the problem.

Please help me, I feel like I'm really close, and the answer to this will help me with data flow from my API for later in my project too.

Thanks so much!

**Comment by h4w5** [comment]
I'll take a look at the code. In the future, link to the relevant code, like:

```
[the button that triggers log in](https://github.com/cameragadget/t_standup_app/blob/master/public/index.html#L31)
```

> Note the `#L31` to reference some line number in the file.

- Template
  - [ControllerAs](https://github.com/cameragadget/t_standup_app/blob/master/public/index.html#L23)
  - [Button](https://github.com/cameragadget/t_standup_app/blob/master/public/index.html#L31)
  - [Name](https://github.com/cameragadget/t_standup_app/blob/master/public/index.html#L30)
- [Controller](https://github.com/cameragadget/t_standup_app/blob/master/public/js/app/auth/trelloSignIn.service.js)

**Comment by h4w5** [comment]
Aha!

Ok, you are reading your user data off of `vm.info`, but that isn't set unless you call the function `onAuthorizeSuccessful()`.
