### ISSUE TITLE
facing a circular dependency issue that I can't resolve

### ISSUE THREAD

**Issue by cameragadget** [cameragadget/t_standup_app#2]
AAU I want to be able to create a new team when I select the trello board from my dropdown menu

error:
Error: $injector:cdep Circular Dependency
https://docs.angularjs.org/error/$injector/cdep?p0=authService%20%3C-%20teamDataService%20%3C-%20trelloApiService%20%3C-%20authService

Attempts to fix: I've been able to make the error disappear by removing dependancies from linked services and controllers, but in doing so, I lose the create team functionality I am trying to create.  it's become a bit of a catch 22 that even Karen can't figure out!

please help me figure this out! I've been working on this user story all day and this last step is a major hurdle I wasn't expecting that's put my forward progress at a standstill.

**Comment by EARnagram** [comment]
Is this closed?

**Comment by cameragadget** [comment]
Sorry, yes, this one is closed. Jim started me on the right path and I have been taking care of it tonight.  wanted to keep it open in case it was not truly gone.  There is now a new issue I have been tackling tonight that will be revealed in the next episode of.... git issues....

thanks guys. have a great night.
